apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web
  labels:
    app: go-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      - name: go-web
        image: hrushikeshazurecicd.azurecr.io/gowebapplication:130
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret 
